PYTHON := ./.venv/bin/python
PYTHONPATH := src:src/aipython

.PHONY: run-point2-forward run-point3-heuristic

run-point2-forward:
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) src/run_point2_forward.py

run-point3-heuristic:
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) src/run_point3_heuristic.py
